query getDCTV {
  domainContentTypeVals {
    nodes {
      id
      key
      short
      long
      keys {
        nodes {
          id
          id1
          id2
          databaseId
        }
      }
    }
  }
}
