/**
 *
 */
export const Constants = {
    PRODUCTION: process.env.NODE_ENV == "production" ? true : false,
    APP_URL: process.env.NEXT_PUBLIC_APP_URL ?? null,
    ROOT: process.env.NEXT_PUBLIC_ROOT ?? null,
    WORDPRESS_URL: process.env.NEXT_PUBLIC_WORDPRESS_URL ?? null,
    WORDPRESS_REST_URL: process.env.NEXT_PUBLIC_WORDPRESS_REST_URL ?? null,
    WORDPRESS_GRAPHQL_ENDPOINT: process.env.NEXT_PUBLIC_WORDPRESS_GRAPHQL_ENDPOINT ?? null,
    ANALYTICS_JS_CONTAINER: process.env.NEXT_PUBLIC_ANALYTICS_JS_CONTAINER ?? null,
    COVER_URL: process.env.NEXT_PUBLIC_COVER_URL ?? null,
    LINKEDIN_CLIENT_ID: process.env.NEXT_PUBLIC_LINKEDIN_CLIENT_ID ?? null,
    LINKEDIN_CLIENT_REDIRECT_URI: process.env.NEXT_PUBLIC_LINKEDIN_CLIENT_REDIRECT_URI ?? null,
    SCOPE: process.env.NEXT_PUBLIC_SCOPE ?? null,
    CATALOG_CARD_WIDTH: process.env.NEXT_PUBLIC_CATALOG_CARD_HEIGHT ?? null,
    CATALOG_HEADER_CARD_WIDTH: process.env.NEXT_PUBLIC_CATALOG_HEADER_CARD_HEIGHT ?? null,
    CATALOG_CARD_HEIGHT: process.env.NEXT_PUBLIC_CATALOG_CARD_HEIGHT ?? null,
    CATALOG_PROMPT_WITDH: process.env.NEXT_PUBLIC_CATALOG_PROMPT_WIDTH ?? null,
    INITIAL_PROCESS_DURATION: process.env.NEXT_PUBLIC_INITIAL_PROCESS_DURATION ?? null,
    PDFJS_EXTERNAL_URL: process.env.NEXT_PUBLIC_PDFJS_EXTERNAL_URL ?? null,
    PDFJS_EXTERNAL_ROOT: process.env.NEXT_PUBLIC_PDFJS_EXTERNAL_ROOT ?? null,
    DEFAULT_USER: process.env.NEXT_PUBLIC_DEFAULT_USER ?? null,
    ADMIN_EMAIL: process.env.NEXT_PUBLIC_ADMIN_EMAIL ?? null,
    ACCESS_TOKEN: process.env.NODE_ENV == "production" ? process.env.ACCESS_TOKEN : ""
}

export const graphqlURI = Constants.WORDPRESS_GRAPHQL_ENDPOINT

