[veepdotai]
title = "Veep.AI Marketing Prompts"
name = "veepdotai"
ns = "app.kermaprojects.marketing.social_network.linkedin"
description = '''
Cette librairie permet de générer les éléments suivants :
* un ensemble de métadonnées pour organiser le stockage et la génération
* un post LinkedIn
* un post LinkedIn amélioré qui s'appuie sur le post précédent

'''
version = 1.0

[owner]
creationDate = "20231219"
author = "JCK"
company = "Veepdotai"

[prompts]
chain = [
'metadata',
'g1',
'g2'
]

[prompts.metadata]
label = "Metadata"
prompt='''
{{inspiration}}

A partir du texte initial ci-dessus, réponds à chaque demande en tant que journaliste professionnel, en français obligatoirement, et au format JSON en respectant le schéma suivant (ne donne pas de tableau) :
{
 "title": un titre accrocheur pour ce texte, sans être pompeux
 "image": le titre du texte
 "description": une description SEO pour ce texte
 "hashtags": une LISTE de 5 hashtags séparés par des ',' pour ce texte
 "themes": une LISTE de 5 thèmes, séparés par des ',' avec le thème principal en premier
 "keywords": une LISTE de 5 mots-clés SEO, séparés par des ','
}
'''

[prompts.g1]
label = "LI v1"
prompt='''
{{inspiration}}

Tu es un journaliste français spécialisé dans les réseaux sociaux. Reformule le texte ci-dessus sous la forme d\'un post linkedin de 200 mots avec des emojis de Noël et des retours à la ligne. Ajoute le mot "FIN".
'''

[prompts.g2]
label = "LI v1++"
prompt = '''
{{g2}}

A partir du texte initial ci-dessus, donne une reformulation du texte initial au format markdown, en français obligatoirement, constituée d\'au moins 5 paragraphes de 200 mots chacun, avec des retours à la ligne. Ajoute le mot "FIN".
'''


