<?php

// autoload_static.php @generated by Composer

namespace WPGraphQL\FacetWP\Vendor\Composer\Autoload;

class ComposerStaticInite65143909b4a4972b68233e63118121b
{
    public static $files = array (
        '8c183e5549a0f2f928d46611cc70ae5e' => __DIR__ . '/../..' . '/access-functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WPGraphQL\\FacetWP\\' => 18,
        ),
        'A' => 
        array (
            'AxeWP\\GraphQL\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WPGraphQL\\FacetWP\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'AxeWP\\GraphQL\\' => 
        array (
            0 => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src',
        ),
    );

    public static $classMap = array (
        'ComposerAutoloaderInite65143909b4a4972b68233e63118121b' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WPGraphQL\\FacetWP\\Autoloader' => __DIR__ . '/../..' . '/src/Autoloader.php',
        'WPGraphQL\\FacetWP\\CoreSchemaFilters' => __DIR__ . '/../..' . '/src/CoreSchemaFilters.php',
        'WPGraphQL\\FacetWP\\Main' => __DIR__ . '/../..' . '/src/Main.php',
        'WPGraphQL\\FacetWP\\Registry\\FacetRegistry' => __DIR__ . '/../..' . '/src/Registry/FacetRegistry.php',
        'WPGraphQL\\FacetWP\\Registry\\TypeRegistry' => __DIR__ . '/../..' . '/src/Registry/TypeRegistry.php',
        'WPGraphQL\\FacetWP\\Type\\Enum\\ProximityRadiusOptions' => __DIR__ . '/../..' . '/src/Type/Enum/ProximityRadiusOptions.php',
        'WPGraphQL\\FacetWP\\Type\\Enum\\SortOptionsEnum' => __DIR__ . '/../..' . '/src/Type/Enum/SortOptionsEnum.php',
        'WPGraphQL\\FacetWP\\Type\\Input\\DateRangeArgs' => __DIR__ . '/../..' . '/src/Type/Input/DateRangeArgs.php',
        'WPGraphQL\\FacetWP\\Type\\Input\\NumberRangeArgs' => __DIR__ . '/../..' . '/src/Type/Input/NumberRangeArgs.php',
        'WPGraphQL\\FacetWP\\Type\\Input\\ProximityArgs' => __DIR__ . '/../..' . '/src/Type/Input/ProximityArgs.php',
        'WPGraphQL\\FacetWP\\Type\\Input\\SliderArgs' => __DIR__ . '/../..' . '/src/Type/Input/SliderArgs.php',
        'WPGraphQL\\FacetWP\\Type\\WPInterface\\FacetConfig' => __DIR__ . '/../..' . '/src/Type/WPInterface/FacetConfig.php',
        'WPGraphQL\\FacetWP\\Type\\WPObject\\Facet' => __DIR__ . '/../..' . '/src/Type/WPObject/Facet.php',
        'WPGraphQL\\FacetWP\\Type\\WPObject\\FacetChoice' => __DIR__ . '/../..' . '/src/Type/WPObject/FacetChoice.php',
        'WPGraphQL\\FacetWP\\Type\\WPObject\\FacetPager' => __DIR__ . '/../..' . '/src/Type/WPObject/FacetPager.php',
        'WPGraphQL\\FacetWP\\Type\\WPObject\\FacetRangeSettings' => __DIR__ . '/../..' . '/src/Type/WPObject/FacetRangeSettings.php',
        'WPGraphQL\\FacetWP\\Type\\WPObject\\FacetSettings' => __DIR__ . '/../..' . '/src/Type/WPObject/FacetSettings.php',
        'WPGraphQL\\FacetWP\\Type\\WPObject\\FacetSortOptionOrderBySetting' => __DIR__ . '/../..' . '/src/Type/WPObject/FacetSortOptionOrderBySetting.php',
        'WPGraphQL\\FacetWP\\Type\\WPObject\\FacetSortOptionSetting' => __DIR__ . '/../..' . '/src/Type/WPObject/FacetSortOptionSetting.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\ConnectionType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/ConnectionType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\EnumType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/EnumType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\FieldsType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/FieldsType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\InputType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/InputType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\InterfaceType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/InterfaceType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\MutationType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/MutationType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\ObjectType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/ObjectType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\Type' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/Type.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Abstracts\\UnionType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/UnionType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Helper\\Compat' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Helper/Compat.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Helper\\Helper' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Helper/Helper.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Interfaces\\GraphQLType' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Interfaces/GraphQLType.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Interfaces\\Registrable' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Interfaces/Registrable.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Interfaces\\TypeWithConnections' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Interfaces/TypeWithConnections.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Interfaces\\TypeWithFields' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Interfaces/TypeWithFields.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Interfaces\\TypeWithInputFields' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Interfaces/TypeWithInputFields.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Interfaces\\TypeWithInterfaces' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Interfaces/TypeWithInterfaces.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Traits\\TypeNameTrait' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Traits/TypeNameTrait.php',
        'WPGraphQL\\FacetWP\\Vendor\\AxeWP\\GraphQL\\Traits\\TypeResolverTrait' => __DIR__ . '/..' . '/axepress/wp-graphql-plugin-boilerplate/src/Traits/TypeResolverTrait.php',
        'WPGraphQL\\FacetWP\\Vendor\\Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'WPGraphQL\\FacetWP\\Vendor\\Composer\\Autoload\\ComposerStaticInite65143909b4a4972b68233e63118121b' => __DIR__ . '/..' . '/composer/autoload_static.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite65143909b4a4972b68233e63118121b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite65143909b4a4972b68233e63118121b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite65143909b4a4972b68233e63118121b::$classMap;

        }, null, ClassLoader::class);
    }
}
